//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
[System.Xml.Serialization.XmlRootAttribute("TMDReport", Namespace="urn://www.fsc.org.au/DDO/TMD/1.0", IsNullable=false)]
public partial class TMDReportType {
    
    private TMDReportHeaderType headerField;
    
    private TMDReportBodyType bodyField;
    
    private TMDReportFooterType footerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TMDReportHeaderType Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public TMDReportBodyType Body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public TMDReportFooterType Footer {
        get {
            return this.footerField;
        }
        set {
            this.footerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDReportHeaderType {
    
    private System.DateTime reportExtractionDateTimeField;
    
    private EntityIdentifierType issuerPrimaryIdentifierField;
    
    private EntityIdentifierType[] issuerAlternativeIdentifiersField;
    
    private CurrentStandardVersion standardVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public System.DateTime ReportExtractionDateTime {
        get {
            return this.reportExtractionDateTimeField;
        }
        set {
            this.reportExtractionDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public EntityIdentifierType IssuerPrimaryIdentifier {
        get {
            return this.issuerPrimaryIdentifierField;
        }
        set {
            this.issuerPrimaryIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Identifier", Namespace="urn://www.fsc.org.au/DDO/Common/1.0", IsNullable=false)]
    public EntityIdentifierType[] IssuerAlternativeIdentifiers {
        get {
            return this.issuerAlternativeIdentifiersField;
        }
        set {
            this.issuerAlternativeIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
    public CurrentStandardVersion StandardVersion {
        get {
            return this.standardVersionField;
        }
        set {
            this.standardVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public partial class EntityIdentifierType {
    
    private EntityIdentifierTypeEnum entityIdentifierType1Field;
    
    private string entityIdentifierValueField;
    
    private string subUnitField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EntityIdentifierType", Order=0)]
    public EntityIdentifierTypeEnum EntityIdentifierType1 {
        get {
            return this.entityIdentifierType1Field;
        }
        set {
            this.entityIdentifierType1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string EntityIdentifierValue {
        get {
            return this.entityIdentifierValueField;
        }
        set {
            this.entityIdentifierValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SubUnit {
        get {
            return this.subUnitField;
        }
        set {
            this.subUnitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum EntityIdentifierTypeEnum {
    
    /// <remarks/>
    FAR,
    
    /// <remarks/>
    ABN,
    
    /// <remarks/>
    ASAL,
    
    /// <remarks/>
    ACL,
    
    /// <remarks/>
    Bespoke,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDReportFooterType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class DistributorReportingRequirementsType {
    
    private bool acquisitionOutsideTMField;
    
    private bool sFCDDOStandardRequiredField;
    
    private DataStandardVersionEnum sFCDDOStandardVersionRequiredField;
    
    private bool sFCDDOStandardVersionRequiredFieldSpecified;
    
    private string alternativeDataStandardField;
    
    private FrequencyOfReportEnum outsideTMDFrequencyOfReportField;
    
    private string outsideTMDReportDeadlineDaysField;
    
    private string complaintsReportingField;
    
    private FrequencyOfReportEnum complaintsFrequencyOfReportField;
    
    private string complaintsReportDeadlineDaysField;
    
    private bool requireSignificantDealingsReportField;
    
    private string appropriatenessField;
    
    public DistributorReportingRequirementsType() {
        this.requireSignificantDealingsReportField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool AcquisitionOutsideTM {
        get {
            return this.acquisitionOutsideTMField;
        }
        set {
            this.acquisitionOutsideTMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool SFCDDOStandardRequired {
        get {
            return this.sFCDDOStandardRequiredField;
        }
        set {
            this.sFCDDOStandardRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public DataStandardVersionEnum SFCDDOStandardVersionRequired {
        get {
            return this.sFCDDOStandardVersionRequiredField;
        }
        set {
            this.sFCDDOStandardVersionRequiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SFCDDOStandardVersionRequiredSpecified {
        get {
            return this.sFCDDOStandardVersionRequiredFieldSpecified;
        }
        set {
            this.sFCDDOStandardVersionRequiredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string AlternativeDataStandard {
        get {
            return this.alternativeDataStandardField;
        }
        set {
            this.alternativeDataStandardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public FrequencyOfReportEnum OutsideTMDFrequencyOfReport {
        get {
            return this.outsideTMDFrequencyOfReportField;
        }
        set {
            this.outsideTMDFrequencyOfReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=5)]
    public string OutsideTMDReportDeadlineDays {
        get {
            return this.outsideTMDReportDeadlineDaysField;
        }
        set {
            this.outsideTMDReportDeadlineDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string ComplaintsReporting {
        get {
            return this.complaintsReportingField;
        }
        set {
            this.complaintsReportingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public FrequencyOfReportEnum ComplaintsFrequencyOfReport {
        get {
            return this.complaintsFrequencyOfReportField;
        }
        set {
            this.complaintsFrequencyOfReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=8)]
    public string ComplaintsReportDeadlineDays {
        get {
            return this.complaintsReportDeadlineDaysField;
        }
        set {
            this.complaintsReportDeadlineDaysField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public bool RequireSignificantDealingsReport {
        get {
            return this.requireSignificantDealingsReportField;
        }
        set {
            this.requireSignificantDealingsReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Appropriateness {
        get {
            return this.appropriatenessField;
        }
        set {
            this.appropriatenessField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum DataStandardVersionEnum {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.0")]
    Item10,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public enum FrequencyOfReportEnum {
    
    /// <remarks/>
    OnEvent,
    
    /// <remarks/>
    EndOfMonth,
    
    /// <remarks/>
    EndOfQuarter,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class DistributionConditionsType {
    
    private bool availableDirectField;
    
    private string directConditionsField;
    
    private bool availableOnPlatformField;
    
    private string platformConditionsField;
    
    private bool availableAdvisedField;
    
    private string advisedConditionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool AvailableDirect {
        get {
            return this.availableDirectField;
        }
        set {
            this.availableDirectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DirectConditions {
        get {
            return this.directConditionsField;
        }
        set {
            this.directConditionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public bool AvailableOnPlatform {
        get {
            return this.availableOnPlatformField;
        }
        set {
            this.availableOnPlatformField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string PlatformConditions {
        get {
            return this.platformConditionsField;
        }
        set {
            this.platformConditionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public bool AvailableAdvised {
        get {
            return this.availableAdvisedField;
        }
        set {
            this.availableAdvisedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string AdvisedConditions {
        get {
            return this.advisedConditionsField;
        }
        set {
            this.advisedConditionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicType {
    
    private TMDCharacteristicEnum characteristicField;
    
    private TMDIndicatorEnum valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public TMDCharacteristicEnum Characteristic {
        get {
            return this.characteristicField;
        }
        set {
            this.characteristicField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public TMDIndicatorEnum Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum TMDCharacteristicEnum {
    
    /// <remarks/>
    InvestmentObjective_CapitalGrowth,
    
    /// <remarks/>
    InvestmentObjective_CapitalPreservation,
    
    /// <remarks/>
    InvestmentObjective_CapitalGuaranteed,
    
    /// <remarks/>
    InvestmentObjective_RegularIncome,
    
    /// <remarks/>
    InvestmentObjective_Specialist,
    
    /// <remarks/>
    ProductUse_SolutionStandalone,
    
    /// <remarks/>
    ProductUse_CoreComponent,
    
    /// <remarks/>
    ProductUse_Satellite,
    
    /// <remarks/>
    InvestmentTimeframe_Short,
    
    /// <remarks/>
    InvestmentTimeframe_Medium,
    
    /// <remarks/>
    InvestmentTimeframe_Long,
    
    /// <remarks/>
    RiskAndReturn_VeryHigh,
    
    /// <remarks/>
    RiskAndReturn_High,
    
    /// <remarks/>
    RiskAndReturn_Medium,
    
    /// <remarks/>
    RiskAndReturn_Low,
    
    /// <remarks/>
    RiskAndReturn_CapitalGuaranteed,
    
    /// <remarks/>
    RedemptionFrequency_Daily,
    
    /// <remarks/>
    RedemptionFrequency_Weekly,
    
    /// <remarks/>
    RedemptionFrequency_Monthly,
    
    /// <remarks/>
    RedemptionFrequency_Quarterly,
    
    /// <remarks/>
    RedemptionFrequency_AnnuallyPlus,
    
    /// <remarks/>
    Liquidity_Low,
    
    /// <remarks/>
    Liquidity_Moderate,
    
    /// <remarks/>
    Liquidity_High,
    
    /// <remarks/>
    Liquidity_VeryHigh,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum TMDIndicatorEnum {
    
    /// <remarks/>
    In,
    
    /// <remarks/>
    Potentially,
    
    /// <remarks/>
    NotConsidered,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsType {
    
    private string investmentObjectiveDescriptionField;
    
    private TMDCharacteristicsTypeInvestmentObjective_CapitalGrowth investmentObjective_CapitalGrowthField;
    
    private TMDCharacteristicsTypeInvestmentObjective_CapitalPreservation investmentObjective_CapitalPreservationField;
    
    private TMDCharacteristicsTypeInvestmentObjective_CapitalGuaranteed investmentObjective_CapitalGuaranteedField;
    
    private TMDCharacteristicsTypeInvestmentObjective_RegularIncome investmentObjective_RegularIncomeField;
    
    private TMDCharacteristicsTypeInvestmentObjective_Specialist investmentObjective_SpecialistField;
    
    private TMDCharacteristicsTypeProductUse_SolutionStandalone productUse_SolutionStandaloneField;
    
    private TMDCharacteristicsTypeProductUse_CoreComponent productUse_CoreComponentField;
    
    private TMDCharacteristicsTypeProductUse_Satellite productUse_SatelliteField;
    
    private TMDCharacteristicsTypeInvestmentTimeframe_Short investmentTimeframe_ShortField;
    
    private TMDCharacteristicsTypeInvestmentTimeframe_Medium investmentTimeframe_MediumField;
    
    private TMDCharacteristicsTypeInvestmentTimeframe_Long investmentTimeframe_LongField;
    
    private TMDCharacteristicsTypeRiskAndReturn_VeryHigh riskAndReturn_VeryHighField;
    
    private TMDCharacteristicsTypeRiskAndReturn_High riskAndReturn_HighField;
    
    private TMDCharacteristicsTypeRiskAndReturn_Medium riskAndReturn_MediumField;
    
    private TMDCharacteristicsTypeRiskAndReturn_Low riskAndReturn_LowField;
    
    private TMDCharacteristicsTypeRiskAndReturn_CapitalGuaranteed riskAndReturn_CapitalGuaranteedField;
    
    private TMDCharacteristicsTypeRedemptionFrequency_Daily redemptionFrequency_DailyField;
    
    private TMDCharacteristicsTypeRedemptionFrequency_Weekly redemptionFrequency_WeeklyField;
    
    private TMDCharacteristicsTypeRedemptionFrequency_Monthly redemptionFrequency_MonthlyField;
    
    private TMDCharacteristicsTypeRedemptionFrequency_Quarterly redemptionFrequency_QuarterlyField;
    
    private TMDCharacteristicsTypeRedemptionFrequency_AnnuallyPlus redemptionFrequency_AnnuallyPlusField;
    
    private TMDCharacteristicsTypeLiquidity_Low liquidity_LowField;
    
    private TMDCharacteristicsTypeLiquidity_Moderate liquidity_ModerateField;
    
    private TMDCharacteristicsTypeLiquidity_High liquidity_HighField;
    
    private TMDCharacteristicsTypeLiquidity_VeryHigh liquidity_VeryHighField;
    
    private string productUseDescriptionField;
    
    private string investmentTimeframeDescriptionField;
    
    private string riskAndReturnDescriptionField;
    
    private string redemptionFrequencyDescriptionField;
    
    private string liquidityDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string InvestmentObjectiveDescription {
        get {
            return this.investmentObjectiveDescriptionField;
        }
        set {
            this.investmentObjectiveDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public TMDCharacteristicsTypeInvestmentObjective_CapitalGrowth InvestmentObjective_CapitalGrowth {
        get {
            return this.investmentObjective_CapitalGrowthField;
        }
        set {
            this.investmentObjective_CapitalGrowthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public TMDCharacteristicsTypeInvestmentObjective_CapitalPreservation InvestmentObjective_CapitalPreservation {
        get {
            return this.investmentObjective_CapitalPreservationField;
        }
        set {
            this.investmentObjective_CapitalPreservationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public TMDCharacteristicsTypeInvestmentObjective_CapitalGuaranteed InvestmentObjective_CapitalGuaranteed {
        get {
            return this.investmentObjective_CapitalGuaranteedField;
        }
        set {
            this.investmentObjective_CapitalGuaranteedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public TMDCharacteristicsTypeInvestmentObjective_RegularIncome InvestmentObjective_RegularIncome {
        get {
            return this.investmentObjective_RegularIncomeField;
        }
        set {
            this.investmentObjective_RegularIncomeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public TMDCharacteristicsTypeInvestmentObjective_Specialist InvestmentObjective_Specialist {
        get {
            return this.investmentObjective_SpecialistField;
        }
        set {
            this.investmentObjective_SpecialistField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public TMDCharacteristicsTypeProductUse_SolutionStandalone ProductUse_SolutionStandalone {
        get {
            return this.productUse_SolutionStandaloneField;
        }
        set {
            this.productUse_SolutionStandaloneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public TMDCharacteristicsTypeProductUse_CoreComponent ProductUse_CoreComponent {
        get {
            return this.productUse_CoreComponentField;
        }
        set {
            this.productUse_CoreComponentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public TMDCharacteristicsTypeProductUse_Satellite ProductUse_Satellite {
        get {
            return this.productUse_SatelliteField;
        }
        set {
            this.productUse_SatelliteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public TMDCharacteristicsTypeInvestmentTimeframe_Short InvestmentTimeframe_Short {
        get {
            return this.investmentTimeframe_ShortField;
        }
        set {
            this.investmentTimeframe_ShortField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public TMDCharacteristicsTypeInvestmentTimeframe_Medium InvestmentTimeframe_Medium {
        get {
            return this.investmentTimeframe_MediumField;
        }
        set {
            this.investmentTimeframe_MediumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public TMDCharacteristicsTypeInvestmentTimeframe_Long InvestmentTimeframe_Long {
        get {
            return this.investmentTimeframe_LongField;
        }
        set {
            this.investmentTimeframe_LongField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public TMDCharacteristicsTypeRiskAndReturn_VeryHigh RiskAndReturn_VeryHigh {
        get {
            return this.riskAndReturn_VeryHighField;
        }
        set {
            this.riskAndReturn_VeryHighField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=13)]
    public TMDCharacteristicsTypeRiskAndReturn_High RiskAndReturn_High {
        get {
            return this.riskAndReturn_HighField;
        }
        set {
            this.riskAndReturn_HighField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public TMDCharacteristicsTypeRiskAndReturn_Medium RiskAndReturn_Medium {
        get {
            return this.riskAndReturn_MediumField;
        }
        set {
            this.riskAndReturn_MediumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=15)]
    public TMDCharacteristicsTypeRiskAndReturn_Low RiskAndReturn_Low {
        get {
            return this.riskAndReturn_LowField;
        }
        set {
            this.riskAndReturn_LowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=16)]
    public TMDCharacteristicsTypeRiskAndReturn_CapitalGuaranteed RiskAndReturn_CapitalGuaranteed {
        get {
            return this.riskAndReturn_CapitalGuaranteedField;
        }
        set {
            this.riskAndReturn_CapitalGuaranteedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=17)]
    public TMDCharacteristicsTypeRedemptionFrequency_Daily RedemptionFrequency_Daily {
        get {
            return this.redemptionFrequency_DailyField;
        }
        set {
            this.redemptionFrequency_DailyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=18)]
    public TMDCharacteristicsTypeRedemptionFrequency_Weekly RedemptionFrequency_Weekly {
        get {
            return this.redemptionFrequency_WeeklyField;
        }
        set {
            this.redemptionFrequency_WeeklyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=19)]
    public TMDCharacteristicsTypeRedemptionFrequency_Monthly RedemptionFrequency_Monthly {
        get {
            return this.redemptionFrequency_MonthlyField;
        }
        set {
            this.redemptionFrequency_MonthlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=20)]
    public TMDCharacteristicsTypeRedemptionFrequency_Quarterly RedemptionFrequency_Quarterly {
        get {
            return this.redemptionFrequency_QuarterlyField;
        }
        set {
            this.redemptionFrequency_QuarterlyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=21)]
    public TMDCharacteristicsTypeRedemptionFrequency_AnnuallyPlus RedemptionFrequency_AnnuallyPlus {
        get {
            return this.redemptionFrequency_AnnuallyPlusField;
        }
        set {
            this.redemptionFrequency_AnnuallyPlusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=22)]
    public TMDCharacteristicsTypeLiquidity_Low Liquidity_Low {
        get {
            return this.liquidity_LowField;
        }
        set {
            this.liquidity_LowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=23)]
    public TMDCharacteristicsTypeLiquidity_Moderate Liquidity_Moderate {
        get {
            return this.liquidity_ModerateField;
        }
        set {
            this.liquidity_ModerateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=24)]
    public TMDCharacteristicsTypeLiquidity_High Liquidity_High {
        get {
            return this.liquidity_HighField;
        }
        set {
            this.liquidity_HighField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=25)]
    public TMDCharacteristicsTypeLiquidity_VeryHigh Liquidity_VeryHigh {
        get {
            return this.liquidity_VeryHighField;
        }
        set {
            this.liquidity_VeryHighField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=26)]
    public string ProductUseDescription {
        get {
            return this.productUseDescriptionField;
        }
        set {
            this.productUseDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=27)]
    public string InvestmentTimeframeDescription {
        get {
            return this.investmentTimeframeDescriptionField;
        }
        set {
            this.investmentTimeframeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=28)]
    public string RiskAndReturnDescription {
        get {
            return this.riskAndReturnDescriptionField;
        }
        set {
            this.riskAndReturnDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=29)]
    public string RedemptionFrequencyDescription {
        get {
            return this.redemptionFrequencyDescriptionField;
        }
        set {
            this.redemptionFrequencyDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=30)]
    public string LiquidityDescription {
        get {
            return this.liquidityDescriptionField;
        }
        set {
            this.liquidityDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentObjective_CapitalGrowth : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentObjective_CapitalPreservation : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentObjective_CapitalGuaranteed : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentObjective_RegularIncome : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentObjective_Specialist : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeProductUse_SolutionStandalone : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeProductUse_CoreComponent : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeProductUse_Satellite : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentTimeframe_Short : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentTimeframe_Medium : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeInvestmentTimeframe_Long : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRiskAndReturn_VeryHigh : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRiskAndReturn_High : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRiskAndReturn_Medium : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRiskAndReturn_Low : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRiskAndReturn_CapitalGuaranteed : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRedemptionFrequency_Daily : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRedemptionFrequency_Weekly : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRedemptionFrequency_Monthly : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRedemptionFrequency_Quarterly : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeRedemptionFrequency_AnnuallyPlus : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeLiquidity_Low : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeLiquidity_Moderate : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeLiquidity_High : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDCharacteristicsTypeLiquidity_VeryHigh : TMDCharacteristicType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public partial class ContactDetailsType {
    
    private string nameField;
    
    private string titleField;
    
    private string phoneField;
    
    private string emailField;
    
    private string addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public partial class ProductIdentifierType {
    
    private ProductIdentifierTypeEnum identifierTypeField;
    
    private string identifierValueField;
    
    private string disambiguationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ProductIdentifierTypeEnum IdentifierType {
        get {
            return this.identifierTypeField;
        }
        set {
            this.identifierTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string IdentifierValue {
        get {
            return this.identifierValueField;
        }
        set {
            this.identifierValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Disambiguation {
        get {
            return this.disambiguationField;
        }
        set {
            this.disambiguationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum ProductIdentifierTypeEnum {
    
    /// <remarks/>
    ISIN,
    
    /// <remarks/>
    SPIN,
    
    /// <remarks/>
    APIR,
    
    /// <remarks/>
    ExchangeId,
    
    /// <remarks/>
    IssuerProvided,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TargetMarketDeterminationType {
    
    private ProductIdentifierType productPrimaryIdentifierField;
    
    private ProductIdentifierType[] productAlternativeIdentifersField;
    
    private string productNameField;
    
    private EntityIdentifierType issuerIdentifierField;
    
    private EntityIdentifierType[] issuerAlternativeIdentifiersField;
    
    private string productIssuerNameField;
    
    private System.DateTime dateApprovedField;
    
    private string tMDVersionField;
    
    private TMDStatusEnum tMDStatusField;
    
    private System.DateTime mandatoryReviewDateField;
    
    private ContactDetailsType contactDetailsField;
    
    private TMDCharacteristicsType tMDCharacteristicsField;
    
    private DistributionConditionsType distributionConditionsField;
    
    private string[] reviewTriggersField;
    
    private DistributorReportingRequirementsType distributorReportingField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ProductIdentifierType ProductPrimaryIdentifier {
        get {
            return this.productPrimaryIdentifierField;
        }
        set {
            this.productPrimaryIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ProductId", Namespace="urn://www.fsc.org.au/DDO/Common/1.0", IsNullable=false)]
    public ProductIdentifierType[] ProductAlternativeIdentifers {
        get {
            return this.productAlternativeIdentifersField;
        }
        set {
            this.productAlternativeIdentifersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ProductName {
        get {
            return this.productNameField;
        }
        set {
            this.productNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public EntityIdentifierType IssuerIdentifier {
        get {
            return this.issuerIdentifierField;
        }
        set {
            this.issuerIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Identifier", Namespace="urn://www.fsc.org.au/DDO/Common/1.0", IsNullable=false)]
    public EntityIdentifierType[] IssuerAlternativeIdentifiers {
        get {
            return this.issuerAlternativeIdentifiersField;
        }
        set {
            this.issuerAlternativeIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string ProductIssuerName {
        get {
            return this.productIssuerNameField;
        }
        set {
            this.productIssuerNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
    public System.DateTime DateApproved {
        get {
            return this.dateApprovedField;
        }
        set {
            this.dateApprovedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=7)]
    public string TMDVersion {
        get {
            return this.tMDVersionField;
        }
        set {
            this.tMDVersionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public TMDStatusEnum TMDStatus {
        get {
            return this.tMDStatusField;
        }
        set {
            this.tMDStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
    public System.DateTime MandatoryReviewDate {
        get {
            return this.mandatoryReviewDateField;
        }
        set {
            this.mandatoryReviewDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public ContactDetailsType ContactDetails {
        get {
            return this.contactDetailsField;
        }
        set {
            this.contactDetailsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public TMDCharacteristicsType TMDCharacteristics {
        get {
            return this.tMDCharacteristicsField;
        }
        set {
            this.tMDCharacteristicsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public DistributionConditionsType DistributionConditions {
        get {
            return this.distributionConditionsField;
        }
        set {
            this.distributionConditionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=13)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ReviewTrigger", IsNullable=false)]
    public string[] ReviewTriggers {
        get {
            return this.reviewTriggersField;
        }
        set {
            this.reviewTriggersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=14)]
    public DistributorReportingRequirementsType DistributorReporting {
        get {
            return this.distributorReportingField;
        }
        set {
            this.distributorReportingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum TMDStatusEnum {
    
    /// <remarks/>
    Available,
    
    /// <remarks/>
    UnderReview,
    
    /// <remarks/>
    StopDistribution,
    
    /// <remarks/>
    Closed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/TMD/1.0")]
public partial class TMDReportBodyType {
    
    private TargetMarketDeterminationType[] tMDsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute("TMD", IsNullable=false)]
    public TargetMarketDeterminationType[] TMDs {
        get {
            return this.tMDsField;
        }
        set {
            this.tMDsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://www.fsc.org.au/DDO/Common/1.0")]
public enum CurrentStandardVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1.0")]
    Item10,
}
